server:
  port: 6060  
 
 
spring:
  application:
    # This ends up as the service name in zipkin
    name: Price Service
  zipkin:
    # Uncomment to send to zipkin, replacing 192.168.99.100 with your zipkin IP address
     baseUrl: ${price.zipkin.url}
  sleuth:
    sampler:
      probability: 1
     
 
